### ISSUE TITLE
Likert Scale Plots (array question)

### ISSUE THREAD

**Issue by lheckmann** [N2-Survey/SurveyFramework#11]
Produces likert figures for the questions with scales used for answers.

![C1_satisfaction_factors_all](https://user-images.githubusercontent.com/74262873/136377397-94f6e368-bb41-41e8-9c1d-f142fe4283b8.png)

Make a function that produces the likert plots for all questions with scales as answers

What should be adjustable:

- [ ] Color Scheme (with a default value that can be set in a header file)
- [ ] Displaying or hiding the question title
- [ ] Figure dimensions (but default set to something reasonable calculated from the number of answer options and distribution)
- [ ] Option for adding spaces between certain bars (e.g. space between Overall satisfaction and the rest in the example figure)
- [ ] Displaying the "No Answers" or hiding them (probably only hiding necessary here)
- [ ] Wrapping option for the text labels in case they get to long

**Comment by kaloeffler** [comment]
@lheckmann could you specify on the spacing option? Should it be only possible for one bar or several? If several should they all have a large space between each other - or be "grouped" - so one could define groups of bars that should have a small spacing between each other and a large one between different groups?

**Comment by lheckmann** [comment]
To keep it as flexible as possible, I would go for the several option.
The grouping you're describing would make sense since I could also define single bars as a group and then get a larger spacing wherever I want it. So small space between each other and large one between different groups I would say.

**Comment by kaloeffler** [comment]
@rguliev 

1)since no Likert plots are available in seaborn / matplotlib per default, I would suggest adapting the following code: https://matplotlib.org/stable/gallery/lines_bars_and_markers/horizontal_barchart_distribution.html#sphx-glr-gallery-lines-bars-and-markers-horizontal-barchart-distribution-py and https://stackoverflow.com/questions/23142358/create-a-diverging-stacked-bar-chart-in-matplotlib/41384812#41384812 (post by eitanlees).

2)Concerning the color scheme we would need some diverging color palette - however, in the default_theme the palette is monochrome. Any wishes or suggestions how to edit the default theme for Likert plots? Do we want to have a default_theme dict for Likert plots as well?


3)Since the choices (list of possible responses to the questions) seem unfortunately not to be sorted from negative over neutral to positive - we need to resort them - since the text contents can be quite arbitrary, I would suggest to make it up to the user to sort them -e.g. provide a list of sorted choices. Besides that I would suggest to have some sorted choices for some standard formulations available and throw an error if no sorting of choices is provided by the user and no sorted list of default choices is available.

4)Same would go for grouping different questions together (see above) - I would make it up to the user to group the questions based on the question label. If no grouping is provided everything is plotted with same spacing.

**Comment by kaloeffler** [comment]
@lheckmann @rguliev 
How do we want to deal with the choices "I don't know"; "I don't want to answer this question", "Does not apply" ? Do we want an option to filter them out? Or have them in the center of the bar? However, there are also questions where a neutral answer exists. Any opinions on that?

**Comment by lheckmann** [comment]
> @lheckmann @rguliev How do we want to deal with the choices "I don't know"; "I don't want to answer this question", "Does not apply" ? Do we want an option to filter them out? Or have them in the center of the bar? However, there are also questions where a neutral answer exists. Any opinions on that?

In the last years we filtered them out at least for the satisfied - dissatisfied arrays (make sure to adjust the total number of responses to the filter). I think it's hard to merge them with the neutral ones without causing confusion. 
But I would leave the option to keep them in (e.g. Having a array question with Yes, No, I don't know - here it makes sense to use the I don't know as a neutral one) - maybe this can be combined with the sorting you describe above? If people input the answers in a certain sorting, they can decide themself if they want to put them in or not. And if they don't mention it in the sorting they are excluded?

I can go over all array questions and come up with default sortings for some of them if you'd like.

**Comment by kaloeffler** [comment]
And idea could be to have the user sort the choices like that:

` sorted_choices = {"negative"["A","B","C"], "neutral":["E","F"], "positive":["G"]}
`
Where the lists for positive and negative are sorted from strongest to weakest.
Based on that the user could e.g. have "Does not apply" or "I don't know" added to "neutral" or not.

**Comment by lheckmann** [comment]
> And idea could be to have the user sort the choices like that:
> 
> `sorted_choices = {"negative"["A","B","C"], "neutral":["E","F"], "positive":["G"]}` Where the lists for positive and negative are sorted from strongest to weakest. Based on that the user could e.g. have "Does not apply" or "I don't know" added to "neutral" or not.

I agree - this sounds like a good idea!

**Comment by kaloeffler** [comment]
After checking all questions and responses - as there can be choices that can be interpreted as positive or negative depending on the question, and also choices where no positive or negative exist I would suggest grouping the choices in 
` sorted_choices = {"left":["A","B","C"], "center":["E","F"], "right":["G"]}`.

**Comment by kaloeffler** [comment]
@lheckmann Please have a look at some example graphs:
![E7b](https://user-images.githubusercontent.com/28811849/146175019-3d5bc2a9-4c42-4811-a3b6-1e089cffe47c.png)
![I2](https://user-images.githubusercontent.com/28811849/146175269-b9d905bd-d940-4fd5-986c-e8ce0191f92c.png)
![I3](https://user-images.githubusercontent.com/28811849/146175310-a90609ea-3811-4570-9247-d643972293fb.png)



**What has been implemented yet:**
- plotting Likert plots with flexible setting of grouped bars and flexible grouping of choices
- default set of presorted choices with the possibility to add a custom sorting by the user : 'sorted_choices = {"left":["A","B","C"], "center":["E","F"], "right":["G"]}' The number of choices can be arbitrary in "left" / "center" and "right"
- color palette - default palette with diverging color scheme for "right" and "left" and grey colors for "center" choices; however plotting can be used with any default color palette as well
- the bars are centered around the choices "center" - since several choices can be assigned to "center" the 0 line does not necessarily need to run through the middle of a bar part
- wrapping of long questions (line breaks)

**What is currently missing**: 
- The number of total answers - here I need an design decision: do we always add the number of total answers given - even if we have filtered out some responses (e.g. "I don't know")?
- How do we want to visualize questions with filtered responses - should they again sum up to 100% and have then a smaller number of responses plotted? Currently certain responses are not selected for the plotting, the answers would not sum up to 100%
- For very long questions there might be the need to shorten them - I would leave this up to the user to prepare the question labels beforehand appropriately
- Is there anything else we need to have implemented?

**Comment by lheckmann** [comment]
@kaloeffler, really nice work, thank you! Also the centering looks nice :) 

First to your questions:
- For the total answers I would adjust them to the filter - otherwise we need to state what we filtered out.
- The percentage should always refer to what you display as the total number of answers: So if we go with the approach above, yes they should add up to 100. If we don't, then they do not need to add up.
- I agree to the long questions - the automatic question title should always be the default as the title of the figure, but one should have the opportunity to change it

And now to what is still missing:
- Using question title as the figure title 
- Can we sort the bars by the amount of positive or negative answers? You see it in the example figure - the factors people are most satisfied with are on top and the least satisfying ones are on the bottom - makes it very easy to grasp what is going on in the figure
- Can we have a white or transparent background?
- The axis do not need to go that far out right? Can they stop at a few percentage over the longest bars?

**Comment by kaloeffler** [comment]
@lheckmann thanks for the input!

total answers: Ok - then we will do the filtering before the plotting and adjust the total answers accordingly and everything will sum up to 100 in the plots.

Concerning the long questions: I would suggest that the user renames the question labels before the plotting - this might also be handy for other question types. Perhaps we could add this as a separate issue?

Concerning the sorting: since the grouping option exists that would allow the user to group and sort the questions to their liking. 
Also there is again the question of what is considered as positive and as negative responses - e.g. "Yes, to a great extend" might be a positive response or a negative depending on the question. So my suggestion would be to handle this though the grouping option - what do you think?

Concerning the axis: usually having a same axis for same plots is preferred, a changing axis throughout the different plots be off putting for some readers. Suggestion: I could add another kwarg to have axis default from 100...100 but it can be cropped. Whats your opinion?

**Comment by lheckmann** [comment]
@kaloeffler 

"I would suggest that the user renames the question labels before the plotting - this might also be handy for other question types. Perhaps we could add this as a separate issue?"
I agree and will bring it up today in the meeting to add it as an issue then.

For the sorting: I would not leave it to the user at least not the default one - e.g. the example figure of the issue: It has so many options and will take quite long for the user to sort it from most satisfied to least. So as default it could be sorted by the positive/negative responses (and that is defined by the user anyway with the sorted_choices option right?) and then with the grouping they could change it maybe?

The option for the axis sounds very good! Small adjustment: 100% to 100% and then one could drop that and specify the max % they would like to display in an option?

**Comment by kaloeffler** [comment]
@lheckmann 

for the sorting: since I have some default grouping of the responses (which will be most of the times (depending on the question)) "left" agreement/ positive and "right" disagreement / negative one could have an option sort by "left" or "right" side of the grouped responses with default by "left"?
I'm just undecided with the grouping option - if it should just allow for grouping and not sorting the questions or both. What do you think?

concerning the axis: I'm wondering in which cases the user might want an arbitrary axis scale? Perhaps you could give me an example in which cases this might be useful? I can just compute the maximum from the provided answers and round it up to x5% or to tenners?

**Comment by lheckmann** [comment]
@kaloeffler 

Left and right is perfectly fine, thank you :) And maybe we have the option: left, right and unsorted? (with left as default)
And for the grouping: I guess we will see what it will be needed for during analysis, but I think we do not need it for sorting, just grouping them after the sorting to make some figure easier to read.

I thought that if the user want to display to graphs on the same page that e.g. one has a max % of 25, the other one of 35%. Then the 100% axis would take up a lot of white space, but still using the same axis might be nice. So the user might want to choose 40% as the max for both figures. Does that make sense?

**Comment by kaloeffler** [comment]
@lheckmann thanks again!

concerning sorting: so I will split grouping questions and sorting them from another.

concerning axis: yes that makes completely sense!

**Comment by kaloeffler** [comment]
@lheckmann concerning the background - I've kept the same "background design" as all other plots currently have. I would suggest editing this in the theme of all plots?

**Comment by lheckmann** [comment]
> @lheckmann concerning the background - I've kept the same "background design" as all other plots currently have. I would suggest editing this in the theme of all plots?

True, thanks for pointing it out!
