### ISSUE TITLE
Plots for comparing distributions

### ISSUE THREAD

**Issue by lheckmann** [N2-Survey/SurveyFramework#19]
Produce plots for comparing distributions of e.g. salary with each other

![B3_salary](https://user-images.githubusercontent.com/74262873/136379157-163fa508-8b54-48f7-ba70-1333e4a5597d.png)

- [x] Make a function that produces the comparison plots for one comparison (e.g. salary by gender)
- [x]  Make a function that produces the comparison plots for more than one comparison (e.g. salary by gender + by nationality)

What should be adjustable:

- [x] Color Scheme (with a default value that can be set in a header file)
- [x] Displaying or hiding the question title
- [x] Figure dimensions (but default set to something reasonable calculated from the number of answer options and distribution)
- [x] Displaying the "No Answers" or hiding them (not sure if needed to be shown here)
- [x] Option for displaying the median as down in the example figure

**Comment by j-pietsch** [comment]
@lheckmann @rguliev 
I have some basic questions before diving in too deep into coding as I am quite new to the structure of the project. My basic idea would be the following (for the case of only one comparison):

1. Add new method to `survey.py` which takes numerical question (e.g. salary), categorical question (e.g. gender) and selected answers of this categorical question (e.g. 'Male', 'Female'), like:
`def plot_comparison(self, question, question_to_compare, selected_answers, ...)` which can be called like:
`s.plot_comparison('B2', 'A6', ['A1', 'A3'])`
Filtering of the answers according to 'Male'/'Female' would also happen in this method.
2. Adjustment of the `count` method would be necessary as we would need counts for these filtered dataframes (and not the whole question dataframe). A dataframe keyword could be used: if not passed, it is ignored; otherwise, it would 'overwrite' question and the counting is done on the passed dataframe:
`def count(self, question: str, dataframe: pd.DataFrame = None, ...`
3. Plotting of multiple subplots in one figure is necessary. This could be done with `single_choice_bar_plot`, but would require to pass fig as well and would complicate a lot of things if you need to adjust spacing/labelling of individual subplots. So I think the best way would be to add a new method `comparison_numeric_bar_plot` in `bar.py` (or even add new file `comparison.py`).

There are some similarities to issue #10 ('Simple comparison plots'), so for the future we could think about using the same function call and maybe preprocessing/filtering. Although I am not too sure about that at the moment.

As these are just my first ideas, let me know if you can think of a better approach or if I am forgetting about something ;)
Thanks!

**Comment by rguliev** [comment]
@j-pietsch Sorry for the late reply.

> 1. Add new method to survey.py which takes numerical question (e.g. salary), categorical question (e.g. gender) and selected answers of this categorical question (e.g. 'Male', 'Female'), like:

I feel like it will require some fixes for allowing more than one split question. But let's start with this and see how it goes:)

> 2. Adjustment of the `count` method would be necessary as we would need counts for these filtered dataframes (and not the whole question dataframe). A dataframe keyword could be used: if not passed, it is ignored; otherwise, it would 'overwrite' question and the counting is done on the passed dataframe:

Yeah, that could be an option. But let's call the argument `responses` instead than `dataframe` since it is more explicit what the dataframe is about. Another option (or we can even use both of them) would be add some arguments to `self.get_responses` so it would accept optional parameter containing choices to drop.

> 3. Plotting of multiple subplots in one figure is necessary. This could be done with single_choice_bar_plot, but would require to pass fig as well and would complicate a lot of things if you need to adjust spacing/labelling of individual subplots. So I think the best way would be to add a new method comparison_numeric_bar_plot in bar.py (or even add new file comparison.py).

I agree. It would be better to create a separate file with a separate function.

**Comment by j-pietsch** [comment]
@lheckmann
So the implementation is roughly finished, the incorporation of the calculation of the median #68 is still to be done.
Currently, two plots are generated by default:

1. Plot for one comparison at a time (up to 8 indivudual comparisons possible)
2. Plot for exactly 2 simultaneous comparisons at a time (up to 8 comparisons possible)

The main question to be filtered is passed as the first argument (e.g. `'B4'`) and all other questions for which the main questions will be filtered are passed as a dict (e.g. `{'A6': ['A1', 'A3'], 'A7': ['A1', 'A2']}`).

I tried to reproduce the plots from above.
The currently shown 'median' is currently just a placeholder.
However, there are some placement problems (of e.g. the labels) because the the figure size varies quite heavily because of the variable input.
When showing additional information (e.g. `show_percents=True`), it gets really messy.


- Is the main layout okay like this? 
- Should the implementation also allow for >2 simultaneous comparisons?
- Should filtered arrays with no entries (see last uploaded image) be excluded or still be shown?

In the following, there are two examplatory function calls with a different number of comparisons:
`s.plot_numeric_comparison('B4', {'A6': ['A1', 'A3'], 'A7': ['A1', 'A2']})`
![Figure_1](https://user-images.githubusercontent.com/96238884/151765338-2fe9f42f-99bf-4c33-8371-77b786f8ecb9.png)
![Figure_2](https://user-images.githubusercontent.com/96238884/151765453-8d2c050e-b222-4199-9b56-43fdd54edc29.png)

`s.plot_numeric_comparison('B2', {'A6': ['A1', 'A3'], 'A7': ['A1', 'A2', 'A3', 'A4']}, show_percents=True)`
![Figure_3](https://user-images.githubusercontent.com/96238884/151769723-461e65d5-22e9-4ab7-a38a-dbe623f98b56.png)
![Figure_4](https://user-images.githubusercontent.com/96238884/151769734-0efb0af5-6564-4a26-819b-6eee9192b453.png)

**Comment by lheckmann** [comment]
Thank you for the work, it looks very nice!

- Is the main layout okay like this?
Yes it is. Just one detail: It's good that the axis adjust to the bar heights as default, but can we include an optional parameter to set the yaxis max? (min should be always 0)

- Should the implementation also allow for >2 simultaneous comparisons?
Probably not necessary right? Would give quite big figures.

- Should filtered arrays with no entries (see last uploaded image) be excluded or still be shown?
Excluded.

- Messy with percentage: There are two things that might help: We can round percentages to integers which takes up less space. And introduce a threshold below which the percentage number is not printing (we do not need the 0.0%), maybe with 5% as default but an optional parameter to change it?
