### ISSUE TITLE
Export aggregate data to file and import aggregate data from file

### ISSUE THREAD

**Issue by fudw** [N2-Survey/SurveyFramework#69]
## Description

As requested by Lea, helper functions are needed for exporting aggregate data for specified questions, i.e. counts and percentages, to a file and importing that data from files. This is needed because raw data from each institute cannot be shared with others and making comparison plots between results from multiple insitutes requires aggregate data only.

## Possible solutions

Methods will be implemented within the LimeSurvey class for exporting and importing, taking question id and file path as argument, respectively.

**Comment by NiRuff** [comment]
For issue # 80, it is necessary to have access to the aggregated data of all institutions, in order to compare these institutions.
For that it would be very helpful, to not have one file per question per institution, but to have one file per institution, that then had to be created and expoerted by a member of each institutions, so that I can work with these files of aggregated data.
Then it is still necessary, to rename questions, as currently the question numbers/names are not synchronized between the three institutions, but this can be my problem then for issue # 80.

I would be happy if I could work with files in this structure:

| Institute| Question| Outcome | Count|
|--------------|-----------|------------|----------|
| Leibniz | A1      | Yes| 18|
| Leibniz | A1      | No| 12|
| Leibniz | ...| ...|...|
| Leibniz | A6      | Male       | 18|
| Leibniz | A6  | Female |25|

(Institute is actually not necessary as I could add this myself, but that is the format that would be practical to work with for me)

**Comment by rguliev** [comment]
![image](https://user-images.githubusercontent.com/9852534/156801334-91496955-834d-40a9-b52e-e27972419d35.png)

**Comment by lheckmann** [comment]
Official okay for sharing the data with excluding the specific institutes and free text questions and permutation is given :)
