### ISSUE TITLE
Design a typical workflow

### ISSUE THREAD

**Issue by rguliev** [N2-Survey/SurveyFramework#8]
It is important to design a typical workflow, so we better coordinate our actions.
In the comments everyone is welcome to provide his/her vision on that.

**Comment by fudw** [comment]
Hi all,

Apology in advance if this sounds dumb as I have zero experience and don't fully understand everything in your discussion above. Would it make sense to divide the the raw data csv into individual dataframes, one for each question? Then each one can be given an attribute indicating what type of question it is, which also determines which type of processing the data should undergo. By question types here I mean something like 

i) Single categorical choice (e.g. nationality); 
ii) Multiple categorical choices (e.g. sources of income); 
iii) Numerical bins (e.g. average hours per week); 
etc... 

I made up these names and I'm sure there are proper jargons, but I hope you get what I mean.

Of course, this assumes that, apart from the already built-in filters that determines which follow-up sub-questions show up, one doesn't care about correlations between multiple questions, like "Among those that answered 'Yes' to Question X, ..." This seems to be the case as far as I can see from the 2019 Report, but please let me know if I missed something. 

Furthermore, one could even pre-make plots of types compatible with the question type and store them in a dict, and the user would simply have to choose from the pre-made plots how they want to visualise the question, and adjust properties of the plots as desired.

I feel like this allows quite a lot of reusability and should be fairly question agnostic, as long as future questions fall under the existing types.

**Comment by rguliev** [comment]
Hi @fudw 

This is makes perfect sense. I would say we are thinking in the same direction.
The only nuance is the technical implementation. In order to do what you described, you do not need separate DataFrames. We will parse a survey structure from the XML file, and then, knowing the structure, we can decide on the type of the question and on the default plot for it. Having survey as a class allow to do this easily and with friendly interface.

**Comment by fudw** [comment]
@rguliev 

Thanks for the clarification. If I understood correctly, the idea is to have a "survey" class containing information about all the questions in the entire questionnaire extracted from the XML file. Then, a class method to fetch and process the data from the csv/dataframe of all the responses to one specific question depending on the type of the question. And finally a function makes the figure given the processed data for that specific question. Is this correct?

**Comment by rguliev** [comment]
Yeah, mostly. The only thing that I would clarify, is that we can load whole csv file. It does not have to be question by question. That is what I meant by:

```python
import n2survey as ns

# Get an instance of a questionnaire with parsed questionnaire structure
# Other possible optional arguments: color_palette, responses file, ?
survey = ns.LimeSurvey("<path to the XML structure file>")

# Read and pre-process all responces. Will be stored as pandas DF
survey.read_responses("<path to responses csv file>")

# ---- This part we mostly discussing now with Oliver ----

# Plot one question. User only provides which question.
# Then the method defines what is the type of the question
# and what is proper default plot type for that kind of question
survey.plot("A1")

# It is also possible to provide to questions like:
survey.plot("A1", split_by="Gender")
```

**Comment by Cheedge** [comment]
Hi guys,

1, agree with you all.
2, agree with Rustan, we don't go deep into implematation. Also, in my opinion the data is really clean. So it is really convinient to read directly by pandas lib. And therefore, it may be better to clearify what we want to do about the "pre-processing". I agree with above talks, the next steps data user should set the standard about what data they prefer to have during their "post-processing" or "plotting' work.
3, I really want to ask about one part of the question data and response data: the 'A(..)#other'(eg. A1other) category. As "A1 question" is "Which institute / section / center are you associated with?", but "A1other" which is not a question label, it is a category label(or value), means "the institute not list above", is also one item of its answer chioces categories. (Here, the survey used similar names, they gives the question tag attribute as A1, and also gives different "values" tags of answer choices as "A1", "A2" ... and "A1other".) But in the response survey file, they were considered as saperated question tags, I think it is not so meaningful, so I changed this part in the read_xml code. I want to know should we treat the survey data different way (I mean different from above you show treating "A1other" as a saperate question rather than a answer category)? (If not, I will change the xml script.)

Best
Q.Z.

**Comment by annaki2021** [comment]
I believe, the problem with the "Other" options is, that we tend not to analyse them (too less manpower), but we give them for completion. Would it be possible to read this information in as differnt questions? So, onece the original question with just the option other and once as separate piece of information containing only the information to this option becuase participants can specify their answer here. I hope, my explanation was not too weird...

**Comment by Cheedge** [comment]
> I believe, the problem with the "Other" options is, that we tend not to analyse them (too less manpower), but we give them for completion. Would it be possible to read this information in as differnt questions? So, onece the original question with just the option other and once as separate piece of information containing only the information to this option becuase participants can specify their answer here. I hope, my explanation was not too weird...

Ok, if I understand correctly, you mean make the "other" option both as a choice item under the question, and also list it out as a saperated question. it seems like a good solution, I will change the script later.

**Comment by rguliev** [comment]
Thank for your comments.
I would suggest to keep discussion specific to the topic. This issue meant to be about a general interface for a user for a typical workflow. Which supposed to help to understand how should we organize our classes, methods, etc.

The issue of "other" answers deserves a separate issue. We will come eventually to it :)
